#!/bin/sh

usage() {
    cat <<EOF
  Usage:
    $0 --OPTIONS* NICKNAME COMMIT

  Re-author COMMIT to NICKNAME, rebasing HEAD atop changes.

  OPTIONS are handled by being passed to weld.

EOF
}

while test -z "${opt_done}"
do
    case "$1"
    in
	--branch | --message )
		WELD_EXTRA_OPTIONS+=" ${1} ${2}"
		shift 2
		;;
        "--"* )
		WELD_EXTRA_OPTIONS+=" ${1}"
		shift
		;;
        * )
		break
		;;
    esac
done

NICKNAME="$1"
COMMIT="${2:-$(git ref $(git symbolic-ref HEAD))}"

weld --reauthor-commit ${NICKNAME} "${COMMIT}"

